# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDoubleSpinBox, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QWidget)

from customqopenglwidget import CustomQOpenGLWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1380, 751)
        MainWindow.setMinimumSize(QSize(1380, 751))
        MainWindow.setMaximumSize(QSize(1380, 751))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1070, 10, 171, 25))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(980, 50, 211, 17))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1260, 50, 61, 20))
        self.pushButton_up = QPushButton(self.centralwidget)
        self.pushButton_up.setObjectName(u"pushButton_up")
        self.pushButton_up.setGeometry(QRect(980, 70, 111, 25))
        self.pushButton_down = QPushButton(self.centralwidget)
        self.pushButton_down.setObjectName(u"pushButton_down")
        self.pushButton_down.setGeometry(QRect(1100, 70, 111, 25))
        self.shift_left_button = QPushButton(self.centralwidget)
        self.shift_left_button.setObjectName(u"shift_left_button")
        self.shift_left_button.setGeometry(QRect(980, 100, 111, 25))
        self.shift_right = QPushButton(self.centralwidget)
        self.shift_right.setObjectName(u"shift_right")
        self.shift_right.setGeometry(QRect(1100, 100, 111, 25))
        self.shift_forward_button = QPushButton(self.centralwidget)
        self.shift_forward_button.setObjectName(u"shift_forward_button")
        self.shift_forward_button.setGeometry(QRect(980, 130, 111, 25))
        self.shift_backward_button = QPushButton(self.centralwidget)
        self.shift_backward_button.setObjectName(u"shift_backward_button")
        self.shift_backward_button.setGeometry(QRect(1100, 130, 111, 25))
        self.scaling_smaller_button = QPushButton(self.centralwidget)
        self.scaling_smaller_button.setObjectName(u"scaling_smaller_button")
        self.scaling_smaller_button.setGeometry(QRect(980, 190, 111, 25))
        self.scaling_bigger_button = QPushButton(self.centralwidget)
        self.scaling_bigger_button.setObjectName(u"scaling_bigger_button")
        self.scaling_bigger_button.setGeometry(QRect(1100, 190, 111, 25))
        self.shift_up_down_spinbox = QDoubleSpinBox(self.centralwidget)
        self.shift_up_down_spinbox.setObjectName(u"shift_up_down_spinbox")
        self.shift_up_down_spinbox.setGeometry(QRect(1260, 70, 65, 26))
        self.shift_z_spinbox = QDoubleSpinBox(self.centralwidget)
        self.shift_z_spinbox.setObjectName(u"shift_z_spinbox")
        self.shift_z_spinbox.setGeometry(QRect(1260, 130, 65, 26))
        self.doubleSpinBox_scale = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_scale.setObjectName(u"doubleSpinBox_scale")
        self.doubleSpinBox_scale.setGeometry(QRect(1260, 190, 65, 26))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(980, 230, 211, 17))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1260, 230, 61, 20))
        self.rotate_up_button = QPushButton(self.centralwidget)
        self.rotate_up_button.setObjectName(u"rotate_up_button")
        self.rotate_up_button.setGeometry(QRect(980, 260, 111, 25))
        self.rotate_down_button = QPushButton(self.centralwidget)
        self.rotate_down_button.setObjectName(u"rotate_down_button")
        self.rotate_down_button.setGeometry(QRect(1100, 260, 141, 25))
        self.rotate_right_button_right = QPushButton(self.centralwidget)
        self.rotate_right_button_right.setObjectName(u"rotate_right_button_right")
        self.rotate_right_button_right.setGeometry(QRect(1100, 300, 141, 25))
        self.rotate_left_button_left = QPushButton(self.centralwidget)
        self.rotate_left_button_left.setObjectName(u"rotate_left_button_left")
        self.rotate_left_button_left.setGeometry(QRect(980, 300, 111, 25))
        self.rotate_counterclockwise_button = QPushButton(self.centralwidget)
        self.rotate_counterclockwise_button.setObjectName(u"rotate_counterclockwise_button")
        self.rotate_counterclockwise_button.setGeometry(QRect(1100, 340, 141, 25))
        self.rotate_clockwise_button = QPushButton(self.centralwidget)
        self.rotate_clockwise_button.setObjectName(u"rotate_clockwise_button")
        self.rotate_clockwise_button.setGeometry(QRect(980, 340, 111, 25))
        self.shift_spinbox = QDoubleSpinBox(self.centralwidget)
        self.shift_spinbox.setObjectName(u"shift_spinbox")
        self.shift_spinbox.setGeometry(QRect(1260, 100, 65, 26))
        self.doubleSpinBox_rotate_up_down = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rotate_up_down.setObjectName(u"doubleSpinBox_rotate_up_down")
        self.doubleSpinBox_rotate_up_down.setGeometry(QRect(1260, 260, 65, 26))
        self.doubleSpinBox_rotate_wise = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rotate_wise.setObjectName(u"doubleSpinBox_rotate_wise")
        self.doubleSpinBox_rotate_wise.setGeometry(QRect(1260, 340, 65, 26))
        self.doubleSpinBox_rotate_left_right = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rotate_left_right.setObjectName(u"doubleSpinBox_rotate_left_right")
        self.doubleSpinBox_rotate_left_right.setGeometry(QRect(1260, 300, 65, 26))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(980, 170, 211, 17))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1260, 170, 61, 20))
        self.label_filename = QLabel(self.centralwidget)
        self.label_filename.setObjectName(u"label_filename")
        self.label_filename.setGeometry(QRect(10, 710, 211, 21))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(250, 710, 51, 21))
        self.label_edges = QLabel(self.centralwidget)
        self.label_edges.setObjectName(u"label_edges")
        self.label_edges.setGeometry(QRect(310, 710, 131, 21))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(540, 710, 61, 21))
        self.label_vertices = QLabel(self.centralwidget)
        self.label_vertices.setObjectName(u"label_vertices")
        self.label_vertices.setGeometry(QRect(610, 710, 131, 21))
        self.OurCustomWidget = CustomQOpenGLWidget(self.centralwidget)
        self.OurCustomWidget.setObjectName(u"OurCustomWidget")
        self.OurCustomWidget.setGeometry(QRect(10, 10, 934, 701))
        self.pushButton_perspective = QPushButton(self.centralwidget)
        self.pushButton_perspective.setObjectName(u"pushButton_perspective")
        self.pushButton_perspective.setGeometry(QRect(1100, 410, 111, 25))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(980, 380, 211, 17))
        self.pushButton_parallel = QPushButton(self.centralwidget)
        self.pushButton_parallel.setObjectName(u"pushButton_parallel")
        self.pushButton_parallel.setGeometry(QRect(980, 410, 111, 25))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(980, 450, 151, 17))
        self.pushButton_Select = QPushButton(self.centralwidget)
        self.pushButton_Select.setObjectName(u"pushButton_Select")
        self.pushButton_Select.setGeometry(QRect(980, 480, 89, 25))
        self.dashed_button = QPushButton(self.centralwidget)
        self.dashed_button.setObjectName(u"dashed_button")
        self.dashed_button.setGeometry(QRect(980, 540, 151, 25))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(980, 520, 211, 17))
        self.horizontalSlider_width = QSlider(self.centralwidget)
        self.horizontalSlider_width.setObjectName(u"horizontalSlider_width")
        self.horizontalSlider_width.setGeometry(QRect(1109, 580, 251, 20))
        self.horizontalSlider_width.setOrientation(Qt.Horizontal)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(980, 580, 101, 17))
        self.pushButton_Select_line = QPushButton(self.centralwidget)
        self.pushButton_Select_line.setObjectName(u"pushButton_Select_line")
        self.pushButton_Select_line.setGeometry(QRect(1140, 480, 89, 25))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(1140, 450, 101, 17))
        self.horizontalSlider_vertex_width = QSlider(self.centralwidget)
        self.horizontalSlider_vertex_width.setObjectName(u"horizontalSlider_vertex_width")
        self.horizontalSlider_vertex_width.setGeometry(QRect(1109, 610, 251, 20))
        self.horizontalSlider_vertex_width.setOrientation(Qt.Horizontal)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(980, 610, 111, 17))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(980, 640, 171, 25))
        self.pushButton_Select_vertex_color = QPushButton(self.centralwidget)
        self.pushButton_Select_vertex_color.setObjectName(u"pushButton_Select_vertex_color")
        self.pushButton_Select_vertex_color.setGeometry(QRect(1260, 480, 89, 25))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(1260, 450, 111, 21))
        self.screenshot_btn = QPushButton(self.centralwidget)
        self.screenshot_btn.setObjectName(u"screenshot_btn")
        self.screenshot_btn.setGeometry(QRect(1010, 680, 121, 25))
        self.record_btn = QPushButton(self.centralwidget)
        self.record_btn.setObjectName(u"record_btn")
        self.record_btn.setGeometry(QRect(1170, 680, 121, 25))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Load from file", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Move figure by a set distance", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.pushButton_up.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.pushButton_down.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.shift_left_button.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.shift_right.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.shift_forward_button.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.shift_backward_button.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
        self.scaling_smaller_button.setText(QCoreApplication.translate("MainWindow", u"Smaller", None))
        self.scaling_bigger_button.setText(QCoreApplication.translate("MainWindow", u"Bigger", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Rotate figure by a set angle", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.rotate_up_button.setText(QCoreApplication.translate("MainWindow", u"Up", None))
        self.rotate_down_button.setText(QCoreApplication.translate("MainWindow", u"Down", None))
        self.rotate_right_button_right.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.rotate_left_button_left.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.rotate_counterclockwise_button.setText(QCoreApplication.translate("MainWindow", u"Counterclockwise", None))
        self.rotate_clockwise_button.setText(QCoreApplication.translate("MainWindow", u"Clockwise", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Scale a figure by a set value", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Custom", None))
        self.label_filename.setText(QCoreApplication.translate("MainWindow", u"file name", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Edges:", None))
        self.label_edges.setText(QCoreApplication.translate("MainWindow", u"count edges", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Vertices:", None))
        self.label_vertices.setText(QCoreApplication.translate("MainWindow", u"count vertices", None))
        self.pushButton_perspective.setText(QCoreApplication.translate("MainWindow", u"perspective", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Set projection", None))
        self.pushButton_parallel.setText(QCoreApplication.translate("MainWindow", u"parallel", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Set background color", None))
        self.pushButton_Select.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.dashed_button.setText(QCoreApplication.translate("MainWindow", u"dashed/solid", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Set line type", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Set line width", None))
        self.pushButton_Select_line.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Set line color", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Set vertex width", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"NONE", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"SQUARE", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"CIRCLE", None))

        self.pushButton_Select_vertex_color.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Set vertex color", None))
        self.screenshot_btn.setText(QCoreApplication.translate("MainWindow", u"Screenshot", None))
        self.record_btn.setText(QCoreApplication.translate("MainWindow", u"Start recording", None))
    # retranslateUi

